services:
  tradernet:
    image: tradernet/tradernet:local
    ports:
      - "8080:8080"
    environment:
      DB_TYPE: POSTGRES
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: tradernet
      DB_USER: tradernet
      DB_PASSWORD: tradernet
    depends_on:
      - postgres
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: tradernet
      POSTGRES_USER: tradernet
      POSTGRES_PASSWORD: tradernet
    ports:
      - "5432:5432"
